[package]
name = "rustos-minimal"
version = "1.0.0"
edition = "2021"
authors = ["RustOS Team"]
description = "RustOS - Minimal Multiboot Kernel"

[[bin]]
name = "rustos-minimal"
path = "src/main_minimal.rs"

[dependencies]
# Bootloader support for bootimage compatibility
bootloader = "0.9.23"

[build-dependencies]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

# Build profiles
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
