[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-unknown-none"

[alias]
# Build aliases for different architectures
build-x86 = "build --target x86_64-rustos.json"
build-arm = "build --lib --target aarch64-apple-rustos.json"
build-lib = "build --lib"

[env]
# Environment variables for cross-compilation
RUST_BACKTRACE = "1"