[package]
name = "rustos-standalone"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "rustos"
path = "src/main.rs"

[dependencies]
bootloader = "0.9.23"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build-dependencies]
cc = "1.0"
